# GENERAL SITE SETTINGS
title: shin2012649 portfolio
baseurl: ""

# LANDING PAGE
username: Shin Hyun Woo
typing_text: 
email: shin2012649@gmail.com
github_username: shin2012649
Blog_username: https://2012649.tistory.com

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: 
about_me_description: "안녕하세요 엔지니어를 꿈꾸는 신현우입니다."

# # SKILLS SECTION
show_skills_card: true
skills_title: Skills
skills_list:
#   - "Amazon AWS"
#   - "Google Cloud"
#   - "Naver Cloud"
#   - "Apache Tomcat"
#   - "Ubuntu"
#   - "Linux"
#   - "Docker"
#   - "Jenkins"
#   - "Nginx"
#   - "Git"
#   - "React"
#   - "HTML5"
#   - "CSS"
#   - "JavaScript"
#   - "Spring"
#   - "MyBatis"
#   - "JPA"
#   - "Python"
#   - "C"
#   - "MySQL"
#   - "Redis"

# TIMELINE SECTION
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://example.com/
timeline_items:
  - date: "2023.04 - 2023.10"
    title: "Naver Cloud Camp"
    description: "Completed the Naver Cloud Camp, gaining hands-on experience with cloud technologies."
  - date: "2022.06 - 2022.12"
    title: "Broccoli Pictures"
    description: "Worked in the film production team, contributing to various aspects of movie-making."
  - date: "2020.03 - 2022.06"
    title: "Republic of Korea Army"
    description: "Served as a Platoon Leader in the 7th Division Search Battalion, achieving valuable leadership and teamwork skills."

# PROJECTS SECTION
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: true
os_projects_title: Open Source Projects

# CONTACT SECTION
show_contact_card: true
contact_title: Contact
contact_description: "감사합니다! "

# GITHUB-METADATA
repository: shin2012649/shin2012649.github.io
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true

# GOOGLE-ANALYTICS
google-analytics:
  id: "UA-158757509-2"

# PLUGINS AND EXCLUSIONS
plugins:
  - "jekyll-github-metadata"

exclude:
  - "_assets"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
