# GENERAL SITE SETTINGS
title: shin2012649
description: shin2012649's Portfolio Website
baseurl: ""

# LANDING PAGE
username: 신현우
typing_text: Shin Hyun Woo's Portfolio Website
email: shin2012649@gmail.com
github_username: shin2012649
blog_username: 2012649

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: About Me
about_me_description: "안녕하세요 우직한 엔지니어를 꿈꾸는 신현우입니다."

# # SKILLS SECTION
show_skills_card: true
skills_title: Skills


# TIMELINE SECTION
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://example.com/

# PROJECTS SECTION
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: false
os_projects_title: Open Source Projects

# CONTACT SECTION
show_contact_card: true
contact_title: Contact
contact_description: "감사합니다! "

# GITHUB-METADATA
repository: shin2012649/shin2012649.github.io
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true

# GOOGLE-ANALYTICS
google-analytics:
  id: "UA-158757509-2"

# PLUGINS AND EXCLUSIONS
plugins:
  - "jekyll-github-metadata"

exclude:
  - "_assets"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
